import 'dotenv/config'

export const env = {
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,

  LOCAL_DEV_APP_HOST: process.env.LOCAL_DEV_APP_HOST,
  LOCAL_DEV_APP_PORT: process.env.LOCAL_DEV_APP_PORT,

  BUILD_MODE: process.env.BUILD_MODE,

  CLIENT_URL: process.env.CLIENT_URL,

  AUTHOR: process.env.AUTHOR,

  WEBSITE_DOMAIN_DEVELOPMENT: process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION: process.env.WEBSITE_DOMAIN_PRODUCTION,

  BREVO_API_KEY: process.env.BREVO_API_KEY,
  ADMIN_EMAIL_ADDRESS: process.env.ADMIN_EMAIL_ADDRESS,
  ADMIN_EMAIL_NAME: process.env.ADMIN_EMAIL_NAME,

  MAILER_SEND_API_KEY: process.env.MAILER_SEND_API_KEY,
  ADMIN_SENDER_EMAIL: process.env.ADMIN_SENDER_EMAIL,
  ADMIN_SENDER_NAME: process.env.ADMIN_SENDER_NAME,

  JWT_ACCESS_TOKEN_SECRET_SIGNATURE: process.env.JWT_ACCESS_TOKEN_SECRET_SIGNATURE,
  JWT_REFRESH_TOKEN_SECRET_SIGNATURE: process.env.JWT_REFRESH_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_CLOUD_KEY: process.env.CLOUDINARY_CLOUD_KEY,
  CLOUDINARY_CLOUD_SECRET: process.env.CLOUDINARY_CLOUD_SECRET
}